name: Gradle
on: [push]
env:
  JAVA_VERSION: '8'
jobs:
  ui:
    name: ui gradle
    runs-on: ubuntu-latest

    steps:
      - name: Git clone
        uses: actions/checkout@v3

      - name: Setup java ${{ env.JAVA_VERSION }}
        uses: actions/setup-java@v3
        with:
          # 'temurin' 'zulu' 'adopt' 'adopt-hotspot' 'adopt-openj9' 'liberica' 'microsoft'
          distribution: 'temurin'
          java-version: ${{ env.JAVA_VERSION }}

      - name: Cache gradle deps ~/.gradle
        uses: actions/cache@v3
        with:
          path: ~/.gradle
          key: ${{ runner.os }}-${{ matrix.os }}-gradle-
          restore-keys: |
            ${{ runner.os }}-${{ matrix.os }}-gradle-
      - name: Build and run everything
        run: |
          cd $GITHUB_WORKSPACE && ./gradlew clean process-resources ui:war
          cd $GITHUB_WORKSPACE && ./gradlew test -x jboss-testcontainers-selenide-local-e2e-tests:test
